FROM ubuntu:16.04

WORKDIR /dist
RUN apt update && apt install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash && apt install -y nodejs 
COPY ./exercise1.10 . 
RUN npm install

EXPOSE 5000
CMD npm start
